config/routes.rb
NkV1::Application.routes.draw do
 
 root 'static_pages#home'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :contact_forms
  resources :pushids
 devise_for :users , :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'} 
 match '/add2calendar', to:'add2gcalendar#push', via: 'get'
 match '/del', to:'add2gcalendar#destroy', via: 'delete'
match '/push2fb', to:'push2fb#push', via: 'get'
match '/refresh', to:'refresh#index', via: 'get'
match '/delfb', to:'push2fb#destroy', via: 'delete'       
match '/sort', to:'refresh#by_date', via:'get' 
match '/myevents', to:'refresh#myevents', via:'get'
match '/hall', to:'refresh#hallevents', via:'get'
match '/campus', to:'refresh#campusevents', via:'get'
match '/approvals', to:'admin#index', via:'get' 
match '/approve', to:'admin#update', via:'get'                        
get "users/preferences"
resources :events do
  put :favorite, on: :member
    put :followfeed, on: :member
      put :share, on: :member
        put :submit, on: :member
      end
resources :users do
   member do
      get :following, :followers
    end
  end
resources :microposts, :only => [:create, :destroy]
resources :relationships, :only => [:create, :destroy]


match '/addevent',   to: 'events#new', via: 'get'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/new_events', to: 'static_pages#new_events', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/our_works', to: 'static_pages#our_works', via: 'get'
  match '/patnerships', to: 'static_pages#patnerships', via: 'get'
  #match '/faq', to: 'static_pages#faq', via: 'get'
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #@title = "Home"
    @events = Event.new
    @events = Event.where("workflow_state=? and edatetime > ?","accept", Time.now).reverse
   # @events = Event.where("sdatetime > ? and sdatetime < ?", Time.now.beginning_of_day + num.day, Time.now.end_of_day + num.day) if num.present?
    @tab1 = Event.where("reach_id = 1 and workflow_state=? and edatetime > ?","accept",Time.now).sort_by{|u| u.updated_at}.reverse     
    @tab2   = Event.where("reach_id = 2 and workflow_state=? and edatetime > ?","accept", Time.now ).reverse 
    @tab5   = Event.where("workflow_state=? and edatetime > ?","accept", Time.now).sort_by{|u| u.shared_by.count}.reverse
###allevents
    
    #@events = Event.all.paginate(:page => params[:page], :per_page => 7)
    @user = current_user || User.new
    @cat_array  = @user.categories #.collect{|p| p.id}
    @dom_array   = @user.domains
    @eli_array  = @user.eligibles
    
    @categor =[]
    @domai = []
    @eligibl = []
         
    @cat_array.each do |u|    
            @cat = Category.find(u.id)
            @categor = @categor << @cat.events.where("workflow_state=? and edatetime > ?","accept", Time.now).pluck(:id)       
        end
 
     @dom_array.each do |u|    
            @dom = Domain.find(u.id)
            @domai = @domai << @dom.events.where("workflow_state=? and edatetime > ?","accept", Time.now).pluck(:id) 
   
           end
        
      @eli_array.each do |u|    
            @eli = Eligible.find(u.id)
            @eligibl = @eligibl << @eli.events.where("workflow_state=? and edatetime > ?","accept", Time.now).pluck(:id) 
              end
    
         @events_array = @categor.flatten << @eligibl.flatten << @domai.flatten
         ids = @events_array.flatten
         sorted_ids = ids.sort_by{|id| ids.select{|id2| id2 == id}.size}.reverse.uniq
         records = Event.find(sorted_ids).group_by(&:id)
         @tab3 = sorted_ids.map { |id| records[id].first }
    @tab4 = @user.userfavorites.where("workflow_state=? and edatetime > ?","accept", Time.now).reverse 
    @tab6 = @user.usershares.where("workflow_state=? and edatetime > ?","accept", Time.now).reverse
    @tab7 = @user.events.reverse          
  end
  
  def new_events
  t = Time.at(params[:created_at].to_i)
     @events = Event.where("updated_at > ?",Time.at(params[:created_at].to_i))
     @user = current_user || User.new
     respond_to do |format|
        format.js
     end
  end
  
  def about
   # @title = "About"
  end
  
  def contact
   # @title = "Contact"
  end
  
  def help
   # @title = "Help"
  end
  
  def faq  
  end
  def tour
  end
  def our_works
  end
  def team
  end
  def partnerships
  end
  def show
     @events = Event.all.reverse
     respond_to do |format|
     format.js
     end
     end
      
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_event.html.erb
<title></title>
<div class="alert alert-dismissable alert-warning eventspc">
      <button type="button" class="close" data-dismiss="alert"> X </button>
        <table class ="table table-striped table-hover eventspc" style="
    table-layout: fixed;">
        <tbody>
        <tr>
        <!-------------------first column---------->
        <td width="7%">
        <%if event.avatar.present?%>
        <%= image_tag event.avatar.url, size: "150x75"%>
        <% else %>
        <%= image_tag 'logo1.png', size: "150x75"%>
       <% end %>
       <br>
       
  <button type="button" class="btn btn-primary btn-xs btn-block"><%= event.reach.name if event.reach.present? %></button> 
  <p class="tour_4"></p>
   <a class="label label-default">Bee Score: <%= event.shared_by.count%></a>
   
        </td>
                <!-------------------second column---------->
         <td width="30%"><div style="word-wrap: break-word;"> <% if @user.userfavorites.include?(event) %>
       
        <%= link_to favorite_event_path(event, type: "unfavorite"),{ method: :put ,:class => "btn btn-primary btn-xs",:style =>"float:right;", title: "unfavorite"} do %><i class="icon icon-star-empty"></i><% end %>
        <% else %>
        <%= link_to favorite_event_path(event, type: "favorite"), {method: :put,:class => "btn btn-primary btn-xs tour_7",title: "favorite",:style =>"float:right;"} do  %><i class="icon icon-star"></i><% end %>
    <% end %>
    
    <%= link_to event.title.titleize,event,{:style => 'font-family: Omnes-Pro,Omnes,"Helvetica Neue",Helvetica,Arial,sans-serif;color: rgb(24, 188, 156);font-style: italic;font-size: 23px;'} %> <br> Organized by : <%=event.organizer%> <% if @user.usershares.include?(event) %>
        <%= link_to share_event_path(event, type: "undo share"), method: :put ,:class => "btn btn-primary btn-xs" do %><i class="icon icon-share">Un-bee it!</i>
        <% end %>
        <% else %>
       <div class="tour_3"><div>
        <%= link_to share_event_path(event, type: "share"), method: :put,:class => "btn btn-primary btn-xs" do %><i class="icon icon-share">Bee it!</i> 
        <% end %>
    <% end %> <button type="button" class="btn btn-success btn-xs" data-container="body" data-toggle="popover" data-placement="top" data-content="<%=event.short_description%>" data-original-title="" title="" style="float: right;"><div class="tour_6">What!?</div></button>
    <table class ="table table-striped table-hover eventspc" style="
    table-layout: fixed;">
    <tbody>
    <tr>
    <td class="eventrow1">
    <b>When</b></td>
            <!-------------------thrid column---------->
    <td class="eventrow2"><%=event.sdatetime.strftime("%d %b %I:%M %p")%> - <%=event.edatetime.strftime("%d %b %I:%M %p")%></td></tr>
    <tr><td class="eventrow1"><b>Where</b></td><td class="eventrow2">
    <%=event.venue%>,<%=event.location%>
    </td></tr>
    <tr><td colspan="2">  
    <div class="tour_7"> </div>
  <% event.categories.each do |d| %> 
           <a class="label label-primary"><%= d.name%></a>    
          <% end %>
          <% event.domains.each do |d| %> 
           <a class="label label-success"><%= d.name%></a>    
          <% end %>
         <% event.eligibles.each do |d| %> 
           <a class="label label-default"><%= d.name%></a>    
          <% end %></td></tr></tbody></table><div></div></td>
         <td class = "aRi" width="20%"> 
         <div class="aU5"><span class="aRh"><%=event.sdatetime.strftime("%b") %></span><span class="aRg"><%=event.sdatetime.day %></span><span class="aRj"><%=event.sdatetime.strftime("%a") %></span></div>
        <div class="tour_5"> 
         <ul class="nav" style="
     margin-left: 0px;margin-right: 0px;">
         <li class="dropdown">
         
         <a href="#" class=" btn btn-primary dropdown-toggle"  data-toggle="dropdown">
                      <i class="icon icon-bell"></i>Alerts!
                      <b class="caret"></b>
                    </a >
                   
          <ul class="dropdown-menu ">
                    <% @push = Pushid.where(:user_id => @user.id, :event_id => event.id).first_or_initialize %>
     <% if @push.gcpush_id.present? %>
         <li><%= link_to @push.gcpush_htmllink do %> Edit alert <i class="icon-google-plus-sign"> </i><% end%></li>
         <li><%= link_to del_path(:id => event.id),method: :delete, data: {confirm: 'Are you sure?'} do %> Delete alert <i class="icon-google-plus-sign""> </i><% end%></li>
         <% else %>
         <li><%= link_to add2calendar_path(:id => event.id) do %> Google alert <i class="icon-google-plus-sign"></i><% end%></li>
         <% end %>
                    <li class="divider"></li>
                   <% if @push.fbpush_id.present? %>
        <li><%= link_to delfb_path(:id => event.id), method: :delete, data: {confirm: 'Are you sure?'} do %>Delete alert <i class="icon-facebook-sign"></i><% end%></li>
         <% else %>
         <li><%= link_to push2fb_path(:id => event.id) do %> Facebook alert <i class=" icon-facebook-sign"></i><% end%></li> 
        
         <% end %>
          <li class="divider"></li>
          <li><a href="https://twitter.com/intent/tweet" class="twitter-share-button" data-lang="en" data-text="<%=event.title %>" data-hashtags="<%=event.organizer%>" data-url="http://kampusbee.com/events/<%=event.id%>" data-count="none"  data-via="<%=event.venue%>,<%= event.location%>" >Tweet</a></li>
          <li class="divider"></li>
                  </ul>
         </li>        
         </ul>
         </div>
         </td>                   
  </tr>
          <!-------------------final top  column---------->
 
                 </tbody>
                 </table>  
               
               </div>
           

app/views/static_pages/_feed.html.erb
<p> Bee Feed: 
<%= @events.count %> events were created <%=time_ago_in_words(@events[0].created_at) %> ago. 

app/views/static_pages/_refresh.html.erb
<%= render partial: "static_pages/event", collection: @events %>

app/views/static_pages/_slider.html.erb
<title></title>
<!%= stylesheet_link_tag  "global.css" %>
<%= javascript_include_tag "jquery.slides.min.js" %>

 <div id="container">
		<div id="slides">
		<figure>
	<%=image_tag "slider-1.jpg", size: "510x205"%>
	<figcaption>

	  <%= Event.first.title %>
	   <%= Event.first.venue %>|<%=Event.first.sdatetime.strftime("%B %d")%>
	</figcaption>
	</figure>
	<figure>
	<%=image_tag "slider-2.jpg", size: "510x205"%>
	<figcaption>
	 <strong> <%= Event.last.title %></strong>
	   <%= Event.last.venue %>|<%=Event.first.sdatetime.strftime("%B %d")%>
	</figcaption>
	</figure>
	<figure>
	<%=image_tag "slider-4.jpg", size: "510x205"%>
	<figcaption>
	  <%= Event.first.title %>
	   <%= Event.first.venue %>|<%=Event.first.sdatetime.strftime("%B %d")%>
	</figcaption>
	</figure>
	<figure>
	<%=image_tag "slider-5.jpg", size: "510x205"%>	
	<figcaption>
	  <%= Event.last.title %>
	   <%= Event.last.venue %>|<%=Event.first.sdatetime.strftime("%B %d")%>
	</figcaption>
        </figure>
  </div>
		
	</div>
	

app/views/static_pages/_slides.html.erb
<%= image_tag

app/views/static_pages/about.html.erb
<title></title> 
  <div class="container" class="clearfix">
    <div class="well" class="clearfix">
    <legend>About Us</legend>
            <p> Campuses are hotspots with loads of activity! It hard to stay informed about the events of your interest.</p>
             <p>Kampusbee is an endeavor to provide an event management platform that is easily accessible for users and organizers. Our primary goal is to capture the activity and keep the user stay informed. 
    <p>We want to connect people with activities not only inside the campus but also across campuses</p>
       <legend> Our Vision</legend>      
     <p>Our vision is to bridge gap between the organizers and attendees</p>

<p>Feel free to send us your feedback! It's just a click away! <%=link_to "Feedback", new_contact_form_path%></p>         
          
	 </div>  
</div>

app/views/static_pages/faq.html.erb
    <!-- End: HEADER -->
    <!-- Start: MAIN CONTENT -->
      <div class="container">
        <div class="page-header">
          <h1>Frequently asked questions</h1>
        </div>  
        <div class="row">
          <div class="span10 offset1">
            <div class="accordion" id="faqAccordion">
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq1">
                      <i class="icon-question-sign"></i> How to add events?
                    </a>
                  </h4>
                </div>
                <div id="faq1" class="accordion-body collapse in">
                  <div class="accordion-inner">
                    <p>
                      It's easy. Go to "add events" link on the top navigation bar. Fill in the details and submit. Anyone can submit an event. The events will be submitted for approval though. User will have scores based on the number of events submitted. We are building a system for users where they get special moderation status for their support eventually. 
                    </p>
                  </div>
                </div>
              </div>
               <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq9">
                      <i class="icon-question-sign"></i> Short description of an event?
                     
                    </a>
                  </h4>
                </div>
                <div id="faq9" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                    It's a 140 characters long description of an event - a Event Tweet. This is <b>mandatory</b> for anyone to add an event. We encourge people to come up with something short about the event.
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq2">
                      <i class="icon-question-sign"></i> How Kampusbee is different from any other event management system?
                    </a>
                  </h4>
                </div>
                <div id="faq2" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                  Colleges are our primary focus. We are never gonna move away from that. A user can set up his preferences. He can check out the events based on his preferences at 'my events' tag. We want to provide all event details easily accessible in the event box. You can set up alerts too by a single click. Isn't it different?  
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq3">
                      <i class="icon-question-sign"></i> What is a Bee Score?
                    </a>
                  </h4>
                </div>
                <div id="faq3" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      Bee score is related to number of users promoting an event. "Here user is a promoter". Bee-it is a way to promote the event. Good bee scores means ample activity happening around the event. The score is internal and kampusbee specific. 
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq4">
                      <i class="icon-question-sign"></i> What if the categories/domains/eligibles that I seek are not available in the events page?
                    </a>
                  </h4>
                </div>
                <div id="faq4" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      Write to us about the new categories/domains/eligible. We give you the access to create your own too for the starters.  
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq5">
                      <i class="icon-question-sign"></i> How do you ensure the event details are right?
                    </a>
                  </h4>
                </div>
                <div id="faq5" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      One way is to check out the event by the kampusbee representative. We want to bring down this process further by adding student ambassador network. Work is going on various moderating levels like hall admin, campus admin to ensure this. Stay tuned to become a Hall kingBee, Campus KingBee etc etc. We would like to hear your solution too. <%= link_to "feedback", new_contact_form_path%>
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq6">
                      <i class="icon-question-sign"></i> What are social alerts?
                    </a>
                  </h4>
                </div>
                <div id="faq6" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      You can push events to get notifications through social networking sites. Just by a single click you can add the event into your google calendars and facebook events. They are all set to defaults - <b>accessible and visible only to you</b>.
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq7">
                      <i class="icon-question-sign"></i> I have a better idea. What should I do?
                    </a>
                  </h4>
                </div>
                <div id="faq7" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                    Even we thought ours was a better idea. It's subjective unless we objectify it with facts. Get in touch with us! We are open to ideas <%= link_to "Feedback", new_contact_form_path%>
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq8">
                      <i class="icon-question-sign"></i> I couldn't sleep for two days what should I do?
                    </a>
                  </h4>
                </div>
                <div id="faq8" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      We certainly don't have an answer for that. Give us more details may be we will get back to you!
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <!-- End: MAIN CONTENT -->
    <!-- Start: FOOTER -->

app/views/static_pages/home.html.erb
   <title>   </title> 
   <script>
    $(window).bind("load", function() {
       $.getScript('<%= asset_path('social.js') %>', function() {});
    });
</script>   
    <!-- Start: MAIN CONTENT -->
    <div class="container">
    
    <div class = "jumbotron">
      <div class="row">
      
    <div class="col-lg-6">
    <h2 class="tour_1" style='font-family: color: #666;font-style: italic;font-size: 30px;' >Stay notified about what's hot inside the campus!</h2>
    <h4 style='font-family: color: #666;font-style: italic;font-size: 20px;' >Here User is a promoter!</h4> 
   <% if signed_in?%>
    <a class="btn btn-primary btn-md" href="<%=addevent_path%>">Add an Event. It's fun :)</a>
    <%else%>
    <a class="btn btn-primary btn-md" href="<%=addevent_path%>">Add an Event. It's easy.</a>
    <%end%>
    <!---<div class="fb-like-box" data-href="http://www.facebook.com/Kampusbeecom" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>--->
    </div>  
    <div class="col-lg-6">    
   	
    <%= render partial: 'static_pages/slider'%> 
    <div class="tour_9"></div>
    <%= javascript_include_tag "slider.js" %>  
    </div>
    </div>
</div>
    <div class="row"> 
 
      <!-- End: slider -->
      <!-- Start: PRODUCT LIST --> 
   
<h2 class="tour_2" id="nav-tabs"></h2>
 <ul class="nav nav-tabs">
 <% if signed_in? %>
<li class="active"><a href="#all" data-toggle="tab">All Events<span class="badge"><%=@events.count%></span></a></li>
<li><a href="#first" data-toggle="tab">Campus Events<span class="badge"><%=@tab1.count%></span></a></li>
<li><a href="#second" data-toggle="tab">Hall Events <span class="badge"><%=@tab2.count%></span></a></li>
<li><a href="#third" data-toggle="tab">My Events<span class="badge"><%=@tab3.count%></span></a></li>
<li><a href="#fourth" data-toggle="tab">My favorites<span class="badge"><%=@tab4.count%></span></a></li>
<li><a href="#fifth" data-toggle="tab">Trending<span class="badge"><%=@tab5.count%></span></a></li>
<li><a href="#sixth" data-toggle="tab">Bee Feed<span class="badge"><%=@tab6.count%></span></a></li>
<li><a href="#seventh" data-toggle="tab">Created Events<span class="badge"><%=@tab7.count%></span></a></li>
<% else %>
<li class="active"><a href="#all" data-toggle="tab">All Events<span class="badge"><%=@events.count%></span></a></li>
<li><a href="#first" data-toggle="tab">Campus Events<span class="badge"><%=@tab1.count%></span></a></li>
<li><a href="#second" data-toggle="tab">Hall Events <span class="badge"><%=@tab2.count%></span></a></li>
<li><a href="#fifth" data-toggle="tab">Trending<span class="badge"><%=@tab5.count%></span></a></li>
<% end %>
</ul>
 <div class="col-lg-2">
    <br>

  
    <div class="list-group">
  <a href="<%= sort_path(:num => 0)%>" class="list-group-item">
    Today
  </a>
  <a href="<%=sort_path(:num => 1)%>" class="list-group-item">Tomorrow
  </a>
  <a href="<%=sort_path(:week => 7)%>" class="list-group-item">This Week
  </a>
  <a href="<%=sort_path(:month => 7)%>" class="list-group-item">This Month
  </a>
 
</div>
<div class="well">
<legend><div class="tour_8"></div>Filter by Date</legend>
<%= form_tag sort_path, :method => :get do %>
 <%= select_date(date = Date.current, order: [:day, :month, :year]) %>
<%=submit_tag ">"%>

   <% end %>

   </div>
   <div class="well">
<legend>Filter by </legend>
<%= form_tag refresh_path, :method => :get do %>
<div class="form-group">
   <%= select("category", "category_id",Category.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Fill Category'},{class: "form-control"}) %>
   
   <%= select("domain", "domain_id", Domain.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Fill Domain'},{class: "form-control"}) %>
   
   <%= select("eligible", "eligible_id", Eligible.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Fill Eligible'},{class: "form-control"}) %>
   
   <%=submit_tag "Filter"%>
   <% end %> 
   </div>
   </div>
</div>

    <div class="col-lg-10">
 <div id="myTabContent" class="tab-content eventstr">
<% if signed_in? %>
<div class="tab-pane fade active in" id="all">
<%= render partial: "static_pages/event", collection: @events %>
</div>
<div class="tab-pane fade" id="first">
<%= render partial: "static_pages/event", collection: @tab1 %> 
</div>
<div class="tab-pane fade" id="second">
<%= render partial: "static_pages/event", collection: @tab2%>        
</div>
<div class="tab-pane fade" id="third">
<%= render partial: "static_pages/event", collection: @tab3 %>        
</div>
<div class="tab-pane fade" id="fourth">

<%= render partial: "static_pages/event", collection: @tab4 %>        
</div>
<div class="tab-pane fade" id="fifth">
<%= render partial: "static_pages/event", collection: @tab5 %>        
</div>
<div class="tab-pane fade" id="sixth">
<%= render partial: "static_pages/event", collection: @tab6 %>        
</div>
<div class="tab-pane fade" id="seventh">
<%= render partial: "static_pages/event", collection: @tab7 %>        
</div>
<%else%>
<div class="tab-pane fade active in" id="all">
<%= render partial: "static_pages/event", collection: @events %>
</div>
<div class="tab-pane fade" id="first">
<%= render partial: "static_pages/event", collection: @tab1 %>        
</div>
<div class="tab-pane fade" id="second">
<%= render partial: "static_pages/event", collection: @tab2 %>        
</div>
<div class="tab-pane fade" id="fifth">
<%= render partial: "static_pages/event", collection: @tab5 %>        
</div>
<%end%>
</div>
</div>
</div>
</div>
<%= render partial: "static_pages/tour" %>
 

<script type="text/javascript" language="javascript" charset="utf-8">
var created_at = <%= Time.now.to_i %>;
window.setInterval(function(){
  $.get('<%= new_events_path %>', {created_at: created_at});
}, 10000);
</script>
  
   
   
    <!-- End: MAIN CONTENT -->

app/views/static_pages/new_events.js.erb
created_at = <%= Time.now.to_i %>;
$("#sixth").prepend("<%= escape_javascript(render partial:'static_pages/feed', collection: @events) %>"); 

app/views/static_pages/team.html.erb
<title></title> 
  <div class="container" class="clearfix">
    <div class="well" class="clearfix">
    <legend>Team</legend>
    <div class="row">   
       <div class="col-lg-2">
           <b> Narendra Karnam, Founder</b>
    <%= image_tag "dev.jpg", :size => '150x190' %>
             		
                                               
                        
                    </div>              
           
        
          <div class="col-lg-10">
             <b> About :</b>
             <p>He is an IIT Khargpur alumnus, graduated in 2011. He had his stints with aviation industry for almost one and half year. He took a break afterwards to find out what's next?. As usual he ran with junta towards CAT, GMAT eventually to realise his motivations and aspirations. Now, he is, in pursuit of his dreams towards "Road less taken".</p>

<p>A self-professed entrepreneurship evangelist, a doer, a ruby enthusiast, a web developer, a risk-taker, pretty-much-fiddle-around-to-make-it-serve-our-purpose-er...and the list goes on...</p>

<p>He respects those who stand up for what they talk and lead by example. The test product was developed by him.</p>
<br>
You can reach him @<a href="mailto:nk06.iitkgp@gmail.com" class="contact-mail">
                 <i class="icon-envelope icon-large"></i>
                </a>
         
    
          </div>
          </div>
	 </div>
	 <div class="well">
	 <legend>Support team for Alpha Release</legend>
	 <p>Special Thanks to Cybrilla Technologies for their immense help with the development.</p>
	<p> Special Thanks to Suraj Sudhakar for his valuable support with the logo for alpha release.</p>
         <p>Thanks to Naveen Karnam for his invaluable suggestions to bring out the product. </p>
<p> Thanks to Sammy for his constant support refining the product. </p>         
	</div>	  
</div>