config/routes.rb
NkV1::Application.routes.draw do
 
 root 'static_pages#home'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :contact_forms
  resources :pushids
 devise_for :users , :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'} 
 match '/add2calendar', to:'add2gcalendar#push', via: 'get'
 match '/del', to:'add2gcalendar#destroy', via: 'delete'
match '/push2fb', to:'push2fb#push', via: 'get'
match '/refresh', to:'refresh#index', via: 'get'
match '/delfb', to:'push2fb#destroy', via: 'delete'       
match '/sort', to:'refresh#by_date', via:'get' 
match '/myevents', to:'refresh#myevents', via:'get'
match '/hall', to:'refresh#hallevents', via:'get'
match '/campus', to:'refresh#campusevents', via:'get'
match '/approvals', to:'admin#index', via:'get' 
match '/approve', to:'admin#update', via:'get'                        
get "users/preferences"
resources :events do
  put :favorite, on: :member
    put :followfeed, on: :member
      put :share, on: :member
        put :submit, on: :member
      end
resources :users do
   member do
      get :following, :followers
    end
  end
resources :microposts, :only => [:create, :destroy]
resources :relationships, :only => [:create, :destroy]


match '/addevent',   to: 'events#new', via: 'get'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/new_events', to: 'static_pages#new_events', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/our_works', to: 'static_pages#our_works', via: 'get'
  match '/patnerships', to: 'static_pages#patnerships', via: 'get'
  #match '/faq', to: 'static_pages#faq', via: 'get'
  
end

app/models/event.rb
class Event < ActiveRecord::Base
#attr_accessor :upload, :edate, :contact_phone 
attr_accessible :title,:organizer,:location,
                            :sdatetime,:edatetime,:contact_name ,
                           :contact_phone, :email,:short_description,
                            :events_description,:venue, :user_id, :avatar,:category_ids,
                 :domain_ids, :eligible_ids,:favorites, :shares, :web,
                 :reach_id,:workflow_state
                                 
validates :title, :presence => true, length: {maximum: 50}
validates_datetime :sdatetime, :after => Time.now + 45.minutes 
validates_datetime :edatetime, :after => :sdatetime
validates :organizer, :presence => true
validates :venue, :presence => true
validates :reach_id, :presence => true
validates :location, :presence => true
validates :events_description, :presence => true
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
validates :short_description, :presence => true, :length => { :maximum => 140}
VALID_PHONE = /([0]|\+91)?[789]\d{9}/
validates :contact_phone, :presence => true, format: { with: VALID_PHONE }
 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment :avatar, :size => { :in => 0..150.kilobytes },
 :content_type => { :content_type => ["image/jpg", "image/gif", "image/png"] }
validates :user_id, :presence => true
has_many :pushids, :dependent => :destroy
has_many :favorites, :dependent => :destroy
has_many :shares, :dependent => :destroy
has_many :followfeeds, :dependent => :destroy
has_and_belongs_to_many :categories
has_and_belongs_to_many :domains
has_and_belongs_to_many :eligibles
belongs_to :user
has_many :favorited_by, through: :favorites, source: :user
has_many :shared_by, through: :shares, source: :user
has_many :followfeeds_by, through: :followfeeds, source: :user
belongs_to :reach
include Workflow
  workflow do
    state :new do
      event :submit, :transitions_to => :being_reviewed
    end
    state :being_reviewed do
      event :accept, :transitions_to => :accepted
      event :reject, :transitions_to => :rejected
    end
    state :accepted
    state :rejected
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_filter :authenticate_user!, except: [:show, :index]
 #:only: [:new, :create ,:blah]
 load_and_authorize_resource :only => [:edit,:update,:destroy]
 def show
   @event = Event.find(params[:id])
   @category=@event.categories
   @domain = @event.domains
   @eligible=@event.eligibles
   @user = current_user || User.new
  end

  # GET /events
  # GET /events.json
  def index
  @user = current_user || User.new
    @events = Event.all
    @events = @events.paginate :page => params[:page], :per_page => 10
      respond_to do |format|
        format.html
        format.atom
      end
  end

  # GET /events/1
  # GET /events/1.json
# before_filter :authenticate_user!
  # GET /events/new
  def new
    @event = Event.new

  
  end

  # GET /events/1/edit
  def edit
  @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
     @event.user_id = current_user.id
     # @event.save!
  if signed_in?
    respond_to do |format|
      if @event.save
            
     # debugger
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
end
   else 
       redirect_to signin_path
       flash[:notice] = 'Please signin first'
   end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
 def update

  @event = Event.find(params[:id]) 
    respond_to do |format|
      if @event.update_attributes(event_params)
       
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def submit
    @event = Event.find(params[:id])
    @event.update_column(:workflow_state,"submit")
    redirect_to @event, notice: "Submitted for approval"
  end
  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    if @event.present?
    @event.destroy
    end
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
    
 def favorite
 @event = Event.find(params[:id])
    type = params[:type]
    if type == "favorite"
      current_user.userfavorites << @event
      redirect_to :back, notice: "You favorited #{@event.title}"

    elsif type == "unfavorite"
      current_user.userfavorites.delete(@event)
      redirect_to :back, notice: "Unfavorited #{@event.title}"

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end
  
  def share
 @event = Event.find(params[:id])
    type = params[:type]
    if type == "share"
      current_user.usershares << @event
      redirect_to :back, notice: "You promoted the event #{@event.title}"

    elsif type == "undo share"
      current_user.usershares.delete(@event)
      redirect_to :back, notice: "Undo promote #{@event.title}"

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:email,:contact_name,:title,:sdatetime,:venue,
      :location,:events_description,:short_description,:email,:user_id,:organizer,
      :edatetime,:contact_phone,{:domain_ids =>[]},{:category_ids =>[]},{:eligible_ids =>[]},:avatar,:web,:reach_id,:workflow_state)                              
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<title></title>	

     <%= stylesheet_link_tag "jquery.datetimepicker.css" %>	
     <%= javascript_include_tag "jquery.datetimepicker.js" %>
                  <%= javascript_include_tag "test.js" %>
                  				
      <div class="container" style="width:1170px">	
      <!-- END SIDEBAR -->
      
        <ul class="breadcrumb">
            <li> <i class="icon-home"></i> <a href="#">Home</a> 
            <span class="divider">/</span> </li>
            <li><a href="#">Events</a> <span class="divider">/</span></li>
            <li>Add Event</li>
          </ul>

              <div class="well">
                  <%= form_for @event,:html => {:novalidate =>'novalidate'} do |u| %>
                  <fieldset>                
                  <span class="label label-primary">Edit Details</span>
                   <span class="label label-default">Preview</span>
                  <span class="label label-default">Submit for Moderation</span>
                  <span class="label label-default">Pending for Moderation</span>
                  <legend><h3>Event Edit Form</h3>
                   </legend>
                  <%= render 'shared/error_messages', :object => u.object %>  
             <br>
             <br>
             <div class="row">
              <div class="col-lg-6">
                    <div id="form-group"> 
                      <!--Competition Title-->
                
               <label class="col-lg-3 control-label">Event Title</label>
                        
                        <div class="col-lg-9">
<%= u.text_field :title, autocomplete: 'off',class: 'form-control' %>
             
                        </div>
                       </div>        
                      <!--Festivals-->
                <!----      <div id="form-group">                  
                          <label class="col-lg-3 control-label">Festival <span>(If any)</span></label>
                      <div class="col-lg-9">
                         <input validateon="blur" autocomplete="off" class="form-control" id="url" name="url" tabindex="2" type="text">
   </div>
   </div>
   
                      <!--Organizers-->
                       <div id="form-group">
                          <label class="col-lg-3 control-label">Organizer</label>
                     <div class="col-lg-9">
                        
                          <%= u.text_field :organizer, autocomplete: 'off',class: 'form-control' %>
                        </div>
                      
                      </div>
                      
                      <!--Website URL-->
                     
                      <div id="form-group">
                          <label class="col-lg-3 control-label">Venue</label>
                     <div class="col-lg-9">
                        
                          <%= u.text_field :venue, autocomplete: 'off',class: 'form-control',:placeholder => 'Building,room no. etc.' %>
                        </div>
                      
                      </div>
   <div id="form-group">
                         
            <label class="col-lg-3 control-label">Location</label>
                        <div class="col-lg-9">
                          <%= u.text_field :location, autocomplete: 'off',class: 'form-control',:placeholder => 'place'  %>
                        </div>
                      </div> 
                      <!--Start date and end date-->
                      <div id="form-group">
                         
                          <label class="col-lg-3 control-label">Event From To</label>
                       <div class="col-lg-9">
                 <%= u.datetime_select :sdatetime, class: 'form-control'%> 
                 <%= u.datetime_select :edatetime,class: 'form-control'%>  
                        </div>
                        
                        </div>
                        
                         <div id="form-group">          <label class="col-lg-3 control-label">Website</label>
                   <div class="col-lg-9">
                         <%= u.url_field :web,class: 'form-control' %>
                        </div>
                     
                      </div>
                      
                  <div id="form-group">
                         
             <label class="col-lg-3 control-label">Short Event Description</label>
                        <div class="col-lg-9">
                 <%= u.text_area :short_description,class: 'form-control',placeholder: "max. 140 characters" %>   <div id='counter'>140</div>
                        </div>
                        </div>
                        <div id="form-group">
                         
                          <label for="url" class="col-lg-3 control-label">Contact Details</label>
                        <div class="col-lg-9 widthLong">
                        <%= u.text_field :contact_name,class: 'form-control',placeholder: 'Name' %>
                        <%= u.text_field :contact_phone,class: 'form-control',placeholder: 'mobile no.' %>
                        <%= u.email_field :email,class: 'form-control',placeholder:'Email Id' %>
                          </div>
                        </div> 
                         
                         <div id="form-group">
                         
                          <label for="url" class="col-lg-3 control-label">Region</label>
                    
                        <div class="col-lg-9">
                          <label style="float:left;padding:8px 20px 8px 0;font-size:14px;" class="col-lg-3 control-label" >
                            <input name="region" value="india" id="region_india" checked="checked" tabindex="2" type="radio">
                            India</label>
                          
                           
                        </div>
                    
                      </div>
                      <div id="form-group">
                         
                          <label class="col-lg-3 control-label">Event Logo</label>
                        <div class="col-lg-9">
                        <%= u.file_field :avatar %> 
                      </div>
                      </div>
                      </div>
                      <!--Location-->
                      
                <div class="col-lg-6">       
                          
                      <!--Domains--><div id="form-group">
                         <br>
                          <label class="col-lg-3 control-label">Event Reach</label>
                       
                        <div class="col-lg-9">
         <%= u.collection_select(:reach_id, Reach.all, :id, :name,include_blank: true) do |b|
                          b.label(class:"btn btn-default category") { b.check_box(class: "hide") + b.text } end %>  
                        </div>
                        
                      </div>
                     <br>
                      
                      <div id="form-group">
                         <br>
                          <label class="col-lg-2 control-label">Domains</label>
                       
                        <div class="col-lg-10">
       <%= u.collection_check_boxes(:domain_ids, Domain.all, :id, :name) do |b|
          b.label(class:"btn btn-default category") { b.check_box(class: "hide") + b.text }
                        end %>
                       
                        </div>
                        
                      </div>
                     <br>
                      <!--Categories-->
                      <div id="form-group">
                      <br>
                          <label class="col-lg-2 control-label">Categories</label>
                        <div class="col-lg-10">
               <%= u.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b|
                          b.label(class:"btn btn-default category") { b.check_box(class: "hide") + b.text }
                        end %>
                       
                        </div>
                      </div>
                      <br>
                      <!--Eligibility-->
                      <div id="form-group">
                         <br>
                          <label class="col-lg-2 control-label">Eligibility</label>
                        <div class="col-lg-10">
                        <%= u.collection_check_boxes(:eligible_ids, Eligible.all, :id, :name) do |b|
                          b.label(class:"btn btn-default category") { b.check_box(class: "hide") + b.text }
                        end %>
                        <br>
                       </div>                                                
                      </div>
			</div>	
			  
                       <!--Competitions Registration URL-->
 
                      <!--Competitions Details-->
                     
                    <div class ="col-lg-9">
                     <div id="form-group">
                         
                          <label class="col-lg-2 control-label">Event Details<br>(For Event Page)</label>
                          
                        <div class="col-lg-10">
                          <%= u.cktext_area :events_description, :class => 'ckeditor',style: 'width: 80%;height: 200px' %>
                          
                        </div>  
                      </div>
                      </div>
                      <div class="col-lg-3">
                      <br>
                      <br><br>
                      <%=u.submit 'Submit Event', class:'btn btn-primary btn-md',type: 'submit' %><br>
                      <%=u.submit'Cancel', class:'btn btn-danger btn-md',type: 'reset' %> 
                      </div>
                      </div>
                      
                       </div> 
                      
                      <!--Attachments-->
                      
                      <!--Deadlines-->
                        
                      </div>                    
                     </fieldset>   
                  <% end %>
                  </div>
      
                </div>
                </div>
                </div>
              <script type="text/javascript" language="javascript" charset="utf-8">
                        $("input[id*='event_domain_ids'],input[id*='event_category_ids'],input[id*='event_eligible_ids']").each(function(){
                                if($(this).prop('checked')){
                                        $(this).parent().removeClass('btn-default');
                                        $(this).parent().addClass('btn-info');
                                }
                        });                </script>
                        <script type="text/javascript" language="javascript" charset="utf-8">
   (function($){$.fn.limiter=function(options){var that=this;options=$.extend({limit:140,counter:$('#counter')},options);var count=function(value,e){var total=options.limit-value.length;if(total>=0){options.counter.text(total)}else{if(e.type=='keypress'){e.preventDefault()}}};return that.each(function(){$(that).on('keypress keyup',function(evt){count($(that).val(),evt)})})}})(jQuery);$('#event_short_description').limiter();
                        </script>

app/views/events/index.html.erb
<title></title> 
      <div class="container">
       <div class="col-lg-2">
    <br>

  
    <div class="list-group">
  <a href="<%= sort_path(:num => 0)%>" class="list-group-item">
    Today
  </a>
  <a href="<%=sort_path(:num => 1)%>" class="list-group-item">Tomorrow
  </a>
  <a href="<%=sort_path(:week => 7)%>" class="list-group-item">This Week
  </a>
  <a href="<%=sort_path(:month => 7)%>" class="list-group-item active">This Month
  </a>
 
</div>
<div class="well">
<legend>Filter by Date</legend>
<%= form_tag sort_path, :method => :get do %>
 <%= select_date(date = Date.current, order: [:day, :month, :year]) %>
<%=submit_tag ">"%>

   <% end %>

   </div>
   <div class="well">
<legend>Filter by </legend>
<%= form_tag refresh_path, :method => :get do %>
<div class="form-group">
   <%= select("category", "category_id",Category.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Fill Category'},{class: "form-control"}) %>
   
   <%= select("domain", "domain_id", Domain.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Fill Domain'},{class: "form-control"}) %>
   
   <%= select("eligible", "eligible_id", Eligible.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Fill Eligible'},{class: "form-control"}) %>
   
   <%=submit_tag "Search"%>
   <% end %> 
   </div>
   </div>
</div> <div class="col-lg-10">
        <div class="page-header">
          <h1>All Events</h1>
        </div>
        <%= render partial: "static_pages/event", collection: @events %> 
        
<%= will_paginate @events, class:"pager" %>
    <%= button_to 'Add Event', addevent_path, method: 'get' %>
    <!-- End: MAIN CONTENT -->
    <!-- Start: FOOTER -->
    </div>
    </div>
     <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <script type="text/javascript" language="javascript" charset="utf-8">
   // <![CDATA[
          $('[data-toggle="popover"]').popover({trigger: 'hover'});
   // ]]>
   </script> 
    

app/views/events/show.html.erb
<title></title>
      <div class="container">
                    <ul class="breadcrumb">
            <li> <i class="icon-home"></i> <a href="#">Home</a> <span class="divider">/</span> </li>
            <li><a href="#">Events</a> <span class="divider">/</span></li>
            <li>Event's Preview</li>
            <li class="fright"><a href="#"><button class="btn btn-info"><i class="icon-plus icon-white"></i> Add New Event</button></a></li>
          </ul>
                        
                                      
                        <div class="well">
                        <legend><h2><%= @event.title %></h2></legend>
                        <h4><b>Organizer: </b><%= @event.organizer %></h4>
                          <div class="row">
                          <div class="col-lg-4">
                            <%if @event.avatar.present?%>
        <%= image_tag @event.avatar.url, size: "300x200"%>
        <% else %>
        <%= image_tag 'logo1.png', size: "300x200"%>
       <% end %>
               
                          </div>
                          <div class="col-lg-4">
                          <% @category.each do |u|%>
                                 <span class="label label-success"><%= u.name%></span>
                                 <% end %> 
                                 <% @domain.each do |u|%>
                                 <span class="label label-primary"><%= u.name%></span>
                                 <% end %> 
                                 <% @eligible.each do |u|%>
                                 <span class="label label-info"><%= u.name%></span>
                                 <% end %> 
                          </div>
                          <div class="col-lg-4">
                          <table class="table table-striped table-hover ">
                           <b>EVENT CONTACT DETAILS</b>
                          <tbody>
                            <tr>
                            <td>Name:</td><td><%=@event.contact_name%></td>
                            </tr>
                            <tr>
                            <td>mail-to:</td><td><%=@event.email %></td>
                            </tr>
                            <tr>
                            <td>mob:</td><td><%=@event.contact_phone %></td>
                            </tr>
                            <td>website:</td><td><%=@event.web %></td>
                            </tr>
                            </tbody>
                            </table>
                          </div>
                          </div>
                          </div>
                          <div class="well">
                          <legend>Event Details</legend>
                          <div class= "row">
                          <div class="col-lg-5">
                          <table class="table table-striped table-hover ">                          
                          <tbody>
                            <tr>
                              <td ><b>Date:</b></td>
                              <td >From: <%=@event.sdatetime.strftime("%B %d,%Y %I:%M %p")%><br> To: <%=@event.edatetime.strftime("%B %d,%Y %I:%M %p")%></td>
                            </tr>
                            <tr>
                             <td><b>Venue:  </b></td>
                                     <td><%=@event.venue %></td>
                                    </tr>
                               <tr>
                                   <td><b>Location:  </b></td>
                                     <td><%=@event.location %></td>
                                    </tr>                                        
                        </tbody></table>
                        </div>
                        <div class="col-lg-5">
                        <b>Short Description</b>
                        
                        <%=@event.short_description %>
                        </div>
                        </div>
                        </div>  
                     <div class="well">
                     <legend>Event Description</legend>
                     <table class="table table-striped table-hover ">
                            <tbody><tr>
                            <td>
                           
                    <%=raw@event.events_description %> </td></tr></tbody></table>
                        
                  
                  <% if @user.events.include?(@event)%> 
                <!% if can? :edit, Event, %>                                     
                 <%= link_to "Edit Event",edit_event_path, :action=>'edit',:type => 'button',:class => 'btn btn-info'%>  
                 <!%end%>
                 <%= link_to "Submit for approval",submit_event_path, :action=>'edit',:type => 'button',method: :put, :class => 'btn btn-info'%>    <% end %>
                 </div>
                   </div>                    
                 </div>
                </div>