config/routes.rb
NkV1::Application.routes.draw do
 
 root 'static_pages#home'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :contact_forms
  resources :pushids
 devise_for :users , :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'} 
 match '/add2calendar', to:'add2gcalendar#push', via: 'get'
 match '/del', to:'add2gcalendar#destroy', via: 'delete'
match '/push2fb', to:'push2fb#push', via: 'get'
match '/refresh', to:'refresh#index', via: 'get'
match '/delfb', to:'push2fb#destroy', via: 'delete'       
match '/sort', to:'refresh#by_date', via:'get' 
match '/myevents', to:'refresh#myevents', via:'get'
match '/hall', to:'refresh#hallevents', via:'get'
match '/campus', to:'refresh#campusevents', via:'get'
match '/approvals', to:'admin#index', via:'get' 
match '/approve', to:'admin#update', via:'get'                        
get "users/preferences"
resources :events do
  put :favorite, on: :member
    put :followfeed, on: :member
      put :share, on: :member
        put :submit, on: :member
      end
resources :users do
   member do
      get :following, :followers
    end
  end
resources :microposts, :only => [:create, :destroy]
resources :relationships, :only => [:create, :destroy]


match '/addevent',   to: 'events#new', via: 'get'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/new_events', to: 'static_pages#new_events', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/our_works', to: 'static_pages#our_works', via: 'get'
  match '/patnerships', to: 'static_pages#patnerships', via: 'get'
  #match '/faq', to: 'static_pages#faq', via: 'get'
  
end

app/views/layouts/_footer.html.erb
     <title></title>
    <footer>
    <div class="navbar navbar-default">
      <div class="container">
        <div class="row">
          
          <div class="col-lg-3">
            <h4><i class="icon-beaker icon-white"></i> About<h4>
            
              <ul class="quick-links">
                <li><a href="<%=about_path%>">About Us</a></li>
                <li><a href="<%=patnerships_path%>">Patnerships</a></li>
                <li><a href="<%=team_path%>">Team</a></li>
                <li><a href="#">Take a Tour</a></li>
              <ul>
                      
          </div>
          <div class="col-lg-3">
            <h4><i class="icon-thumbs-up icon-white"></i> Support</h4>
            
              <ul class="quick-links">
                <li><a href="<%=faq_path%>">FAQ</a></li>
                <li><a href="<%=new_contact_form_path%>">Contact us</a></li>            
              </ul>
            
         <!---   <i class="icon-legal icon-white"></i> Legal
            
              <ul class="quick-links">
                <li><a href="#">License</a></li>
                <li><a href="#">Terms of Use</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Security</a></li>      
              </ul>----->
                      
          </div>
          <div class="col-lg-3">
            <h4>Get in touch</h4>
            <div class="social-icons-row">
              <a href="#"><i class="icon-twitter"></i></a>
              <a href="#"><i class="icon-facebook"></i></a>
              <a href="#"><i class="icon-google-plus"></i></a>             <a href="mailto:kampusbee@gmail.com"><i class="icon-envelope"></i></a>                            
            </div>
            
            <div class="social-icons-row">
              <i class="icon-phone icon-large phone-number"></i> +918884056308
            </div>
          </div>      
          <div class="col-lg-3">
           <!--- <h4>Get updated by email</h4>
            <form>
              <input type="text" name="email" placeholder="Email address">
              <input type="submit" class="btn btn-primary" value="Subscribe">
            </form>--->
          </div>
        </div>
      </div>
      <hr class="footer-divider">
      <div class="container">
        <p>
          &copy; 2014-3000 Kampusbee.com, Inc. All Rights Reserved.
        </p>
      </div>
      </div>
    </footer>
    <!-- End: FOOTER -->

app/views/layouts/_header.html.erb
 <title></title>
    
 <header>
      <!-- Start: Navigation wrapper -->
      <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<%= root_path %>">Kampusbee.com </a>
       <!----     <div class="logo">
            <%= image_tag 'logo1.png', size: "130x60"%>
            </div>
            <!-- Below button used for responsive navigation -->
  <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
           </div> 
            <div class="navbar-collapse collapse navbar-responsive-collapse">
            <!-- Start: Primary navigation -->
                    
              <ul class="nav navbar-nav navbar-right">
                            
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="<%=about_path%>">About Us</a></li>
                        <li><a href="<%=patnerships_path%>">Partnerships</a></li>
                        <li><a href="<%=team_path%>">Team</a></li>
                        <li class="divider"></li>
                    
                      </ul>
                      
                    </li>
                     <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Events <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="<%= addevent_path %>">Add Events</a></li>
                        <li><a href="<%= myevents_path %>">My Events</a></li>
                        <li><a href="<%= hall_path %>">Hall Events</a></li>
                        <li><a href="<%= campus_path %>">Campus Events</a></li>
                        <li><a href="<%= events_path%>">All Events</a></li>
                        <li class="divider"></li>
             
                      </ul>
                     
                    </li>
                    <li><a href="<%= faq_path %>">FAQ</a></li>
                    <li><a href="<%= contact_path %>">Contact Us</a></li>                    
                  <% if user_signed_in? %>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Feeds<b class="caret"></b></a>
                  <ul class="dropdown-menu">
            <li><%= link_to "My Feeds", '#' %></li>
            <li><%= link_to "Following Feeds", '#' %></li>
            <li><%= link_to "Bee Feeds", '#' %></li>
            </ul> 
              <% if current_user.has_role? :superadmin %>
            <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                  <ul class="dropdown-menu">
            <li><%= link_to "Rails Admin", rails_admin_path %></li>
            <li><%= link_to "Approvals", approvals_path %></li>
            </ul> 
             <% end %>          
             	  <li class="dropdown">
             	  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.name%> | Account<b class="caret"></b></a>
                  <ul class="dropdown-menu">                  
         <li><%= link_to "All Users",users_path %></li>
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "User Settings", edit_user_path(current_user) %></li> 
                  <li><%= link_to "Preferences", users_preferences_path %></li>  
                  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>     
         </ul>             
         <% else %>      
                <li><%= link_to "Sign in", new_user_session_path %></li> 
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
                  
                  </ul>
                  
            </div>
            </div>
           </div>         
      <!-- End: Navigation wrapper -->   
    </header>
    <!-- End: HEADER -->

app/views/layouts/_shim.html.erb
 <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->

<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Kampusbee.com | Stay informed! ">
    <meta name="author" content="Narendra">
    <title>Kampusbee.com</title>
    <!-- Bootstrap -->
     <%= stylesheet_link_tag  "application" %>    
     <!%= stylesheet_link_tag  "bootstrap.min" %>
    <%= stylesheet_link_tag  "bootstrap-responsive.min" %>
    <%= stylesheet_link_tag  "font-awesome.min" %>
    <%= stylesheet_link_tag  "font-awesome-ie7" %>
    <%= stylesheet_link_tag  "boot-business" %>
    <%= stylesheet_link_tag  "jquery.jquerytour" %>
    <!%= stylesheet_link_tag  "jquery-ui" %> 
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
     <%= javascript_include_tag "jquery-ui.min.js" %>
     <!%= javascript_include_tag :defaults %>     
    <%= csrf_meta_tags %>
          
<%= render 'layouts/shim' %>
</head>
<body>
<div id="bbb">
  <a href="<%=root_path%>">Alpha Release</a>
</div> 
 <div id="feedback">
 <p class="tour_10"></p>
  <a href="<%=new_contact_form_path%>">Feedback</a>
</div> 

<!---
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=235140026659021";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script> --->

 <%= render 'layouts/header' %> 
<%= render partial: "shared/flash_messages", flash: flash %>
 
   <%= yield %>
    <script type="text/javascript" language="javascript" charset="utf-8">
   // <![CDATA[
          $('[data-toggle="popover"]').popover({trigger: 'hover'});
   // ]]>
   </script> 
   <%= render 'layouts/footer' %>
    
    
   <%= debug(params) if Rails.env.development? %>

  </body>
</html>